#!/bin/sh
mountroot()
{
    ROOTTMPFSSIZE='500M';
    for x in $(cat /proc/cmdline); do
        case $x in
            roottmpfssize=*)
                ROOTTMPFSSIZE=${x#roottmpfssize=}
                echo "Root tmpfs size is $ROOTTMPFSSIZE"
                sleep 1
            ;;
        esac
    done

    modprobe nfs
    modprobe af_packet
    modprobe aufs
    udevadm trigger
    wait_for_udev 5
    configure_networking
    test -d /nfsroot || mkdir /nfsroot
    test -d /ramdisk || mkdir /ramdisk
    test -d /${rootmnt} || mkdir ${rootmnt}
    sleep 3

    mount -t tmpfs -o rw,size=$ROOTTMPFSSIZE tmpfs /ramdisk
    retry_nr=0
    max_retry=30
    while [ ${retry_nr} -lt ${max_retry} ] && [ ! -e /nfsroot/${init} ]; do
        log_begin_msg "Trying nfs mount"
        nfsmount -o nolock,ro  ${NFSOPTS} ${NFSROOT} /nfsroot
        /bin/sleep 1
        retry_nr=$(( ${retry_nr} + 1 ))
        log_end_msg
    done
    # overlay /ramdisk(rw) over /nfsroot(ro) and mount it on /
    mount -t aufs -o dirs=/ramdisk=rw:/nfsroot=ro none ${rootmnt}
    echo ${hostname} > ${rootmnt}/etc/hostname
    echo "cluster" > ${rootmnt}/etc/defaultdomain
    echo "live-node" > ${rootmnt}/etc/debian_chroot
    
}
 

